// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXe-rVlDmtwQq_uUBGyoDookbpmKE4HD4',
    appId: '1:947469660128:web:214f95ef3787daad5e0585',
    messagingSenderId: '947469660128',
    projectId: 'gen-z-ai-facee',
    authDomain: 'gen-z-ai-facee.firebaseapp.com',
    storageBucket: 'gen-z-ai-facee.firebasestorage.app',
    measurementId: 'G-M28JBP4XGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAspsRp3bf3lHpCw9jediVT788NIuP0imY',
    appId: '1:947469660128:android:2c179b700d9b0ba95e0585',
    messagingSenderId: '947469660128',
    projectId: 'gen-z-ai-facee',
    storageBucket: 'gen-z-ai-facee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByX5vQhjcBVHfz4mIJEnvoDf8zayqOdr0',
    appId: '1:947469660128:ios:fea0f7023adeea4c5e0585',
    messagingSenderId: '947469660128',
    projectId: 'gen-z-ai-facee',
    storageBucket: 'gen-z-ai-facee.firebasestorage.app',
    iosBundleId: 'com.example.voiceAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByX5vQhjcBVHfz4mIJEnvoDf8zayqOdr0',
    appId: '1:947469660128:ios:fea0f7023adeea4c5e0585',
    messagingSenderId: '947469660128',
    projectId: 'gen-z-ai-facee',
    storageBucket: 'gen-z-ai-facee.firebasestorage.app',
    iosBundleId: 'com.example.voiceAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXe-rVlDmtwQq_uUBGyoDookbpmKE4HD4',
    appId: '1:947469660128:web:2623e8c67983ab675e0585',
    messagingSenderId: '947469660128',
    projectId: 'gen-z-ai-facee',
    authDomain: 'gen-z-ai-facee.firebaseapp.com',
    storageBucket: 'gen-z-ai-facee.firebasestorage.app',
    measurementId: 'G-SQCPKH0SKF',
  );
}
